### ISSUE TITLE
Does it work with 8920w thermostat 

### ISSUE THREAD

**Issue by omegartlx** [chamberlain2007/aprilaire-ha#22]
My new home comes with a full apriaire HVAC system so I need to know if it works.

**Comment by chamberlain2007** [comment]
@omegartlx Unfortunately, according to some who have tried it, the 8920W is not compatible - see https://community.home-assistant.io/t/aprilaire-thermostat-8800-any-modbus-experts/341414/136?u=chamberlain2007 . That said, I do not have that particular unit, so I can't verify this myself. When you close on your house, you can definitely have a look and see if it's possible to put it into Automation mode which is required in order for this integration to work.
