### ISSUE TITLE
8810M Not Connecting. Unknown Error Occured or Connection Failed, depending on port.

### ISSUE THREAD

**Issue by hollywoodscotty** [chamberlain2007/aprilaire-ha#28]
I have enabled Automation mode using the installation guide for this model. I have successfully connected a different model to my Home Assistant instance. IP confirmed correct by comparing MAC on device to MAC on network using arp-a command. IP Address pings. Device communicates with Aprilaire mobile app. Attempted ports 7000 and 8000. Field data reads "(usually 7000 or 8000)", wondering if there is a way to determine which port(s) can be tested.

**Comment by hollywoodscotty** [comment]
Attempted 7001 and 8001, both resulted in an immediate "Unknown Error Occurred" error. Port 8000 is the only one that loads for ~30 seconds, and reads Connection failed. Port 8000 was used for my other Aprilaire device successfully.

**Comment by chamberlain2007** [comment]
@hollywoodscotty Unfortunately I have not seen anything documented from Aprilaire about which port is used consistently. Their documentation on these aspects is really poor, to the extent that I don't even have a concrete list of which _devices_ are supported (Aprilaire themselves couldn't provide a list).

If it fails immediately, then that almost definitely is not the right port. If it hangs for 30 seconds, then that means that it connected to the port but that it isn't responding with some data (the timeout is 30 seconds).

If you haven't already, I recommend power cycling the thermostat, as they can get in a state where they don't respond to sockets at all.

If it still fails after power cycling, then you can try enabling debug logging in HA and sending the output. Set this in your configuration.yaml, restart Home Assistant, wait till everything is initialized and then clear the log. Then go re-add the device and copy the resulting debug lines from your log. You can comment out the log and reboot once you have logs for the first minute or so after adding.

logger:
  default: error
  logs:
    custom_components.aprilaire: debug

**Comment by MicroDraco** [comment]
Any updates on this? I own the same model.

**Comment by chamberlain2007** [comment]
This integration has been merged to Home Assistant core and will not receive future updates here.
