### ISSUE TITLE
Warning Messages / Incorrect Reporting

### ISSUE THREAD

**Issue by ADeadPixel** [chamberlain2007/aprilaire-ha#3]
With the latest update the integration is throwing the following warning message
```
2023-01-03 11:23:27.112 WARNING (MainThread) [custom_components.aprilaire] Received extra data from request
```

As a result the integration is reporting either unavailable, random information, and the wrong status. This may be a result of my two zone system or the new status update.

**Comment by ADeadPixel** [comment]
Here is an example of how the card / integration looks.

![image](https://user-images.githubusercontent.com/53877960/210409365-371a137d-7efd-436e-b4bb-89e41cf4445f.png)

![image](https://user-images.githubusercontent.com/53877960/210409438-a24a9e3f-b922-4a7d-aad0-aaeeb814fcef.png)

**Comment by chamberlain2007** [comment]
I would think it's more related to your two zone system. The recent changes relate to being able to display the heating/cooling status which I see correct on your card, and the rounding of Fahrenheit temperatures on the sensors to whole numbers to match the logic on the device.

The warning you see is when the thermostat basically sends multiple messages in the same socket write. It then tries to parse the whole message as one which is of course invalid. It happens occasionally, but the only impact would be occasionally stale data. I have thoughts on how to split these types of data better, but for now I haven't seen any negative impacts from my side.

**Comment by ADeadPixel** [comment]
Ahhhhhh, so the status is what the unit is currently doing not the mode it is set to! I was confused then. 

I wasn't seeing the extra data messages until recently. But that being said I wasn't monitoring it super closely either. Stale data does happen occasionally or it'll show the upstairs zone or just 0's for certain parts of it. Makes sense that it is just getting confused with the extra messages getting sent.

**Comment by chamberlain2007** [comment]
Yes exactly. If you don't provide the current action, it displays the current mode there. I added the action so now it shows that.

I'll probably get you to provide a bit of data for the multi-zone so that I can figure out the format, I'm assuming it comes through like a normal status with an extra data point, hence it sometimes showing one vs the other.

Im going to close this issue and I'll get a task opened for that.
