### ISSUE TITLE
Fresh Air Event Service - Auto vs Off

### ISSUE THREAD

**Issue by ShinobiAlchemist** [chamberlain2007/aprilaire-ha#33]
@ShinobiAlchemist I have completed the humidity/dehumidity, fresh air and air cleaning.

- Humidity will appear on the climate entity detail if supported
- Dehumidity is a new service as home assistant does not yet support humidity ranges in the UI like it does with temperatures
- There is a service for triggering and canceling fresh air ventilation and air cleaning

Please test this if possible with your devices by enabling Beta mode for the integration and installing the latest. https://hacs.xyz/docs/faq/beta/

I don't have humidity or air cleaning on my physical system, so while I tested against a mock server, I don't have a physical device to test those against.

Please let me know if you have a chance to test and if there are any issues. Ideally I would like to release this 1-2 weeks from now.

_Originally posted by @chamberlain2007 in https://github.com/chamberlain2007/aprilaire-ha/issues/14#issuecomment-1522674371_

Thanks again for your help on #14! 

I've just realized on the 8840 when I call the service "Aprilaire: Cancel fresh air event", it sets the permanent mode to Automatic. Is there an option for a service to set the mode to Off?

The context here is when the mode is Automatic, the controller for the intake in the attic is allowed to run the unit based on it's programming, while Off overrides it.

**Comment by chamberlain2007** [comment]
@ShinobiAlchemist Good catch, you are absolutely correct. The behavior that the device and official app follow is to use the currently selected mode unchanged when activating/deactivating an event. The integration was force setting this which it shouldn't. I have updated this and it should work as expected. This will be in the 0.7.2 release in the next few days.

**Comment by ShinobiAlchemist** [comment]
Awesome! The way I figured it out was quite interesting. I was experiencing a temperature imbalance in the house (Arizona heat) and for the life of me couldn't locate the source. Had a little chat with an engineer at work and he said if I think of my house as a closed system, hot air is being dumped in from somewhere...and that's when I had the ah-ha moment. Thanks as always for your support!

**Comment by chamberlain2007** [comment]
This has been released in 0.7.2. Thanks!
