### ISSUE TITLE
Change in the Thermostat IP is not picked up automatically

### ISSUE THREAD

**Issue by JDNEU** [chamberlain2007/aprilaire-ha#45]
Hi, My Thermostat IPs changed after router upgrade. I can see HA integration captured mac addresses of these two thermostats. However, reinitializing still doesn't work.

**Comment by chamberlain2007** [comment]
If your IP address has changed, simply remove the integration and re-add it with the new IP.

**Comment by JDNEU** [comment]
Oh ok, thank you for the update
